version: "3.1"
services:
  # run container of updated Dockerfile image
  server:
    image: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    depends_on:
      - database
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://database:27017/dev_db
      - MONGO_TEST_URL=mongodb://database:27017/test_db
  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
volumes:
  mongo-data:
