GET http://localhost:3000/
################################
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "userName": "Steven",
    "password": "adminadmin123",
    "role": "admin"
}

################################
GET http://localhost:3000/api/auth/google

################################
GET http://localhost:3000/api/auth/logout


################################
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "userName": "Steven",
    "password": "adminadmin123",
    "role": "admin"
}
