GET http://localhost:3000/
################################
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "userName": "Steven",
    "password": "adminadmin123"
}

################################
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "userName": "John Cena",
    "password": "123456"
}

################################
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "userName": "The Rock",
    "password": "123456"
}

################################
GET http://localhost:3000/api/auth/logout


################################
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "userName": "Darwin",
    "password": "password",
    "role": "customer"
}

################################
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "userName": "Darwin",
    "password": "password"
}

